Ticket number 10012 - Cypress_assertions
TetianaZholudova/CypressTest pull request #3
Opened 2024-07-17 08:02 UTC by TetianaZholudova

Hello Stanislav, 
please take a look and review my PR

2024-07-17 08:25 UTC, sttaran requested changes

2024-07-17 08:25 UTC, sttaran commented on cypress/e2e/emailValidation.cy.js
> +    registrationPageStepsEmailField.leaveEmailFieldEmpty()
it is overhead

2024-07-17 08:25 UTC, sttaran commented on cypress/e2e/emailValidation.cy.js
> +    registrationPageStepsEmailField.leaveEmailFieldEmpty()
for this scenario two cypress methods would be enough 

https://docs.cypress.io/api/commands/blur
https://docs.cypress.io/api/commands/focus

2024-07-17 08:25 UTC, sttaran commented on cypress/e2e/emailValidation.cy.js
> +    registrationPageStepsEmailField.enterIncorrectEmail()
enterIncorrectEmail does not represent what this method actually does

it does not enter anything

it checks validation

2024-07-18 05:24 UTC, TetianaZholudova commented
Hello Stanislav, 
I have refactored the code according to your comments. Please review and approve or advise on further improvements

2024-07-18 15:26 UTC, sttaran approved these changes

2024-07-23 15:25 UTC, merged